$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$port = 80
$portFile = Join-Path $projectRoot "ngrok_upstream_port.txt"
if (Test-Path $portFile) {
  $line = (Get-Content $portFile -TotalCount 1).Trim()
  if ($line -match '^\d+$') { $port = [int]$line }
}

function Test-LocalHttp([string]$url) {
  try {
    $r = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 3
    return ($r.StatusCode -ge 200 -and $r.StatusCode -lt 500)
  } catch {
    return $false
  }
}

$upstream = "http://127.0.0.1:$port"
$autoDetected = $false

# If no explicit port file, auto-detect a live local upstream.
if (-not (Test-Path $portFile)) {
  $candidates = @(
    @{ upstream = "http://127.0.0.1:80";   probe = "http://127.0.0.1:80/elderly-app/" },
    @{ upstream = "http://127.0.0.1:8080"; probe = "http://127.0.0.1:8080/elderly-app/" },
    @{ upstream = "http://127.0.0.1:3000"; probe = "http://127.0.0.1:3000/" },
    @{ upstream = "http://127.0.0.1:5173"; probe = "http://127.0.0.1:5173/" },
    @{ upstream = "http://127.0.0.1:4173"; probe = "http://127.0.0.1:4173/" }
  )
  foreach ($c in $candidates) {
    if (Test-LocalHttp $c.probe) {
      $upstream = $c.upstream
      $autoDetected = $true
      break
    }
  }
  if (-not $autoDetected) {
    throw "No local web service detected on 80/8080/3000/5173/4173. Start Apache (XAMPP) or run npm run dev, then retry."
  }
}

$yaml = @"
# Generated by scripts/write-ngrok-config.ps1 - do not edit by hand.
# Set explicit upstream via ngrok_upstream_port.txt (one line, e.g. 80 or 8080).
# Without that file, this script auto-detects a live local service (80/8080/3000/5173/4173).
version: 3

endpoints:
  - name: elderly-app
    url: https://
    upstream:
      url: $upstream
"@
$out = Join-Path $projectRoot "ngrok.generated.yml"
Set-Content -Path $out -Value $yaml -Encoding utf8
Write-Host "ngrok upstream: $upstream -> ngrok.generated.yml"
