$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$port = 80
$portFile = Join-Path $projectRoot "ngrok_upstream_port.txt"
if (Test-Path $portFile) {
  $line = (Get-Content $portFile -TotalCount 1).Trim()
  if ($line -match '^\d+$') { $port = [int]$line }
}
$upstream = "http://127.0.0.1:$port"
$yaml = @"
# Generated by scripts/write-ngrok-config.ps1 - do not edit by hand.
# Set Apache listen port via ngrok_upstream_port.txt (one line, e.g. 80 or 8080).
version: 3

endpoints:
  - name: elderly-app
    url: https://
    upstream:
      url: $upstream
"@
$out = Join-Path $projectRoot "ngrok.generated.yml"
Set-Content -Path $out -Value $yaml -Encoding utf8
Write-Host "ngrok upstream: $upstream -> ngrok.generated.yml"
